<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeetingRecord.AccessDatas\MeetingRecord.AccessDatas.csproj" />
    <ProjectReference Include="..\MeetingRecord.Dtos\MeetingRecord.Dtos.csproj" />
    <ProjectReference Include="..\MeetingRecord.Models\MeetingRecord.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Adapter\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
